version: 2.1

references:
  defaults: &defaults
      docker:
        - image: circleci/openjdk:8-jdk
          auth:
            username: $DOCKER_HUB_USERNAME
            password: $DOCKER_HUB_TOKEN

jobs:
  build:
    <<: *defaults
    steps:
      - run:
          name: Downloading Dependencies
          command: echo -e "downloading stuff... \n stuff downloaded!!!"
          
      - run:
          name: Building Project
          command: |
            echo "running ./gradlew build..."
            echo "building..."
            echo "built!!!"
  publish:
    <<: *defaults
    steps:
      - run:
          name: Build, Test, Publish Artifacts
          command: |
            echo "running ./gradlew publish..."
            echo "publishing..."
            echo "published!!!"
  release:
    <<: *defaults
    steps:
      - run:
          name: Configure Github
          command: |
            echo "running git config --global user.name ryli123"
            echo "running git config --global user.email ****@gmail.com"
      - run:
          name: Release and Publish Artifacts
          command: |
            echo "running ./gradlew release..."
            echo "releasing..."
            echo "released!!!"

# Orchestrate or schedule a set of jobs
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
      - publish:
          requires:
            - build
          filters:
            branches:
              only: master
      - release:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
              
