version: 2

# Use a package of configuration called an orb.
orbs:
  welcome: circleci/welcome-orb@0.4.1

jobs:
  build:
    steps:
      - run:
        - name: Downloading Dependencies
        - command: |
          echo "downloading stuff..."
          echo "stuff downloaded!!!"
          
      - run:
        - name: Building Project
        - command: |
          echo "running ./gradlew build..."
          echo "building..."
          echo "built!!!"
  publish:
    steps:
      - run:
        - name: Build, Test, Publish Artifacts
        - command: |
          echo "running ./gradlew publish..."
          echo "publishing..."
          echo "published!!!"
  release:
    steps:
      - run:
        - name: Configure Github
        - command: |
          echo "running git config --global user.name ryli123"
          echo "running git config --global user.email ****@gmail.com"
      - run:
        - name: Release and Publish Artifacts
        - command: |
          echo "running ./gradlew release..."
          echo "releasing..."
          echo "released!!!"

# Orchestrate or schedule a set of jobs
workflows:
  version: 2
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - welcome/run:
        filters:
          branches:
            ignore: master
  build:
    jobs:
      - build
      - publish:
        requires:
          - build
        filters:
          branches:
            ignore: master
      - release:
        requires:
          - build
        filters:
          branches:
            only: master
